name: setup go

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup go
        id: go
        uses: actions/setup-go@v2.1.3

      - name: second
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}