name: setup go

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}

      - name: setup go
        id: go
        uses: actions/setup-go@v2.1.3
 
   
 
      - name: Build
        run: go build 
              
      - name: Build2
        run: go run main.go
 
 

      - name: Test
        run: go version
 

